on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit tests.
        run: |
          echo ${{ github.ref_name }}
